version: "3.7"

services:

  bws-react:
    build:
      context: .
      dockerfile: dockerfile
    
    image: bws-react
    container_name: bws-react
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - stdf-tool_stdft
      
networks:
  stdf-tool_stdft:
    external: true